apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: s3-input-sensor
  labels:
    sensors.argoproj.io/sensor-controller-instanceid: argo-events
spec:
  repeat: true
  serviceAccountName: argo-events-sa
  imageVersion: "v0.6"
  signals:
    - name: s3-gateway/input
  triggers:
    - name: argo-workflow
      resource:
        namespace: argo-events
        group: argoproj.io
        version: v1alpha1
        kind: Workflow
        parameters:
          - src:
              signal: s3-gateway/input
              path: s3.object.key
            dest: spec.templates.0.container.args.0
          - src:
              signal: s3-gateway/input
              path: s3.bucket.name
            dest: spec.templates.0.container.args.1
        source:
          inline: |
            apiVersion: argoproj.io/v1alpha1
            kind: Workflow
            metadata:
              generateName: process-image-
            spec:
              entrypoint: process-image
              serviceAccountName: argo-events-sa
              templates:
                - name: process-image
                  container:
                    image: metalgearsolid/minio-image-processing:latest
                    args:
                      - this will be replaced
                      - input
                    env:
                      - name: NAMESPACE
                        valueFrom:
                          fieldRef:
                            fieldPath: metadata.namespace
                      - name: CONFIG_MAP
                        value: minio-access-configmap
                      - name: SERVICE_ACCOUNT_NAME
                        value: argo-events-sa