apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: s3-output-sensor
  labels:
    sensors.argoproj.io/sensor-controller-instanceid: argo-events
spec:
  repeat: true
  serviceAccountName: argo-events-sa
  imageVersion: "v0.6"
  signals:
    - name: s3-gateway/output
  triggers:
    - name: argo-workflow
      resource:
        namespace: argo-events
        group: argoproj.io
        version: v1alpha1
        kind: Workflow
        source:
          inline: |
            apiVersion: argoproj.io/v1alpha1
            kind: Workflow
            metadata:
              generateName: pipeline-completed-
            spec:
              entrypoint: whalesay
              serviceAccountName: argo-events-sa
              templates:
                - name: whalesay
                  container:
                    args:
                      - "Image Processing Pipeline Completed"
                    command:
                      - cowsay
                    image: "docker/whalesay:latest"
